openapi: 3.0.3
info:
  title: Microservice BrainTank
  description: Microservice BrainTank
  version: 1.0.0
servers:
  - url: '/api/brain-tank'
    description: WISdoM

  - url: 'http://localhost:8000'
    description: Development

components:
  securitySchemes:
    WISdoM:
      description: |
        Access Tokens issued by the User Management Service
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

paths:
  /v1/insert:
     post:
        responses:
          201:
            description: Insert response
            content:
              text/plain:
                schema:
                  type: string
  